# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Información básica del sitio
title: "Mi Sitio Hacker"
description: "Un sitio con estilo hacker para pentesting y labs."
url: "https://tusitio.com"
baseurl: ""

<<<<<<< HEAD
# Navegación dinámica
nav:
  - name: "Home"
    url: "/"
  - name: "Labs"
    url: "/labs/"
  - name: "About"
    url: "/about/"
  - name: "Contact"
    url: "/contact/"
  - name: "Blog"
    url: "/blog/"

# Configuración de colecciones (si es necesario)
collections:
  labs:
    output: true
    permalink: /labs/:path/

# Plugins de Jekyll (si necesitas alguno)
=======
# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
>>>>>>> 5d37ff89a8dd67fd82099a4fda57ad77426b2f47
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown y sintaxis
markdown: kramdown
highlighter: rouge

# Tema visual
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
